<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Aeges.Core\Aeges.Core.csproj" />
    <ProjectReference Include="..\Aeges.Storage\Aeges.Storage.csproj" />
    <ProjectReference Include="..\Aeges.Runners\Aeges.Runners.csproj" />
    <ProjectReference Include="..\Aeges.Git\Aeges.Git.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
