// <auto-generated />
using System;
using Aeges.Storage.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aeges.Storage.Sqlite.Migrations
{
    [DbContext(typeof(AegesDbContext))]
    [Migration("20260512065553_AddProjectRootsAndGroups")]
    partial class AddProjectRootsAndGroups
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Aeges.Storage.Sqlite.Entities.ApprovalRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("IterationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("iteration_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<string>("RequestedAction")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("requested_action");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("resolved_at");

                    b.Property<string>("ResolvedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("resolved_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("task_id");

                    b.HasKey("Id");

                    b.HasIndex("IterationId");

                    b.HasIndex("Status");

                    b.HasIndex("TaskId");

                    b.ToTable("approvals", (string)null);
                });

            modelBuilder.Entity("Aeges.Storage.Sqlite.Entities.ArtifactRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("IterationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("iteration_id");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("relative_path");

                    b.Property<string>("Sha256")
                        .HasColumnType("TEXT")
                        .HasColumnName("sha256");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("size_bytes");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("task_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("IterationId");

                    b.HasIndex("TaskId");

                    b.HasIndex("Type");

                    b.ToTable("artifacts", (string)null);
                });

            modelBuilder.Entity("Aeges.Storage.Sqlite.Entities.LockRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("PathPattern")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("path_pattern");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("released_at");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("task_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ReleasedAt");

                    b.HasIndex("TaskId");

                    b.ToTable("locks", (string)null);
                });

            modelBuilder.Entity("Aeges.Storage.Sqlite.Entities.MachineRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("platform");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("machines", (string)null);
                });

            modelBuilder.Entity("Aeges.Storage.Sqlite.Entities.ProjectGroupRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("archived_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IsArchived");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("project_groups", (string)null);
                });

            modelBuilder.Entity("Aeges.Storage.Sqlite.Entities.ProjectRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("archived_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("GroupId")
                        .HasColumnType("TEXT")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("IsArchived");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Aeges.Storage.Sqlite.Entities.ProjectRootRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("archived_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IsArchived");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("project_roots", (string)null);
                });

            modelBuilder.Entity("Aeges.Storage.Sqlite.Entities.RunnerExecutionRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("Cancelled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("cancelled");

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("command");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("exit_code");

                    b.Property<string>("IterationId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("iteration_id");

                    b.Property<string>("RunnerId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("runner_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("task_id");

                    b.Property<bool>("TimedOut")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("timed_out");

                    b.Property<string>("WorkingDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("working_directory");

                    b.HasKey("Id");

                    b.HasIndex("IterationId");

                    b.HasIndex("RunnerId");

                    b.HasIndex("TaskId");

                    b.ToTable("runner_executions", (string)null);
                });

            modelBuilder.Entity("Aeges.Storage.Sqlite.Entities.RuntimeEventRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("event_type");

                    b.Property<string>("IterationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("iteration_id");

                    b.Property<string>("MachineId")
                        .HasColumnType("TEXT")
                        .HasColumnName("machine_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("payload_json");

                    b.Property<string>("TaskId")
                        .HasColumnType("TEXT")
                        .HasColumnName("task_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EventType");

                    b.HasIndex("IterationId");

                    b.HasIndex("MachineId");

                    b.HasIndex("TaskId");

                    b.ToTable("runtime_events", (string)null);
                });

            modelBuilder.Entity("Aeges.Storage.Sqlite.Entities.TalkMessageRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SessionId");

                    b.ToTable("talk_messages", (string)null);
                });

            modelBuilder.Entity("Aeges.Storage.Sqlite.Entities.TalkSessionRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("archived_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalSessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("external_session_id");

                    b.Property<string>("RunnerId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("runner_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Source");

                    b.HasIndex("Status");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("talk_sessions", (string)null);
                });

            modelBuilder.Entity("Aeges.Storage.Sqlite.Entities.TaskIterationRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DiffArtifactId")
                        .HasColumnType("TEXT")
                        .HasColumnName("diff_artifact_id");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("failure_reason");

                    b.Property<int>("IterationNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("iteration_number");

                    b.Property<string>("PromptArtifactId")
                        .HasColumnType("TEXT")
                        .HasColumnName("prompt_artifact_id");

                    b.Property<string>("ResultArtifactId")
                        .HasColumnType("TEXT")
                        .HasColumnName("result_artifact_id");

                    b.Property<string>("RunnerId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("runner_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("task_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorktreePath")
                        .HasColumnType("TEXT")
                        .HasColumnName("worktree_path");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("TaskId");

                    b.HasIndex("TaskId", "IterationNumber")
                        .IsUnique();

                    b.ToTable("task_iterations", (string)null);
                });

            modelBuilder.Entity("Aeges.Storage.Sqlite.Entities.TaskRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentIteration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("current_iteration");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("failure_reason");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("goal");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("machine_id");

                    b.Property<int>("MaxIterations")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(3)
                        .HasColumnName("max_iterations");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("priority");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Status");

                    b.HasIndex("Status", "Priority", "CreatedAt");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("Aeges.Storage.Sqlite.Entities.TransportCallbackActionRecord", b =>
                {
                    b.Property<string>("Transport")
                        .HasColumnType("TEXT")
                        .HasColumnName("transport");

                    b.Property<string>("Token")
                        .HasColumnType("TEXT")
                        .HasColumnName("token");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("action_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_used_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload_json");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("scope");

                    b.Property<int>("UseCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("use_count");

                    b.HasKey("Transport", "Token");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Transport", "Scope");

                    b.ToTable("transport_callback_actions", (string)null);
                });

            modelBuilder.Entity("Aeges.Storage.Sqlite.Entities.ApprovalRecord", b =>
                {
                    b.HasOne("Aeges.Storage.Sqlite.Entities.TaskIterationRecord", "Iteration")
                        .WithMany("Approvals")
                        .HasForeignKey("IterationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Aeges.Storage.Sqlite.Entities.TaskRecord", "Task")
                        .WithMany("Approvals")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Iteration");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Aeges.Storage.Sqlite.Entities.ArtifactRecord", b =>
                {
                    b.HasOne("Aeges.Storage.Sqlite.Entities.TaskIterationRecord", "Iteration")
                        .WithMany("Artifacts")
                        .HasForeignKey("IterationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Aeges.Storage.Sqlite.Entities.TaskRecord", "Task")
                        .WithMany("Artifacts")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Iteration");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Aeges.Storage.Sqlite.Entities.LockRecord", b =>
                {
                    b.HasOne("Aeges.Storage.Sqlite.Entities.ProjectRecord", "Project")
                        .WithMany("Locks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Aeges.Storage.Sqlite.Entities.TaskRecord", "Task")
                        .WithMany("Locks")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Aeges.Storage.Sqlite.Entities.ProjectRecord", b =>
                {
                    b.HasOne("Aeges.Storage.Sqlite.Entities.ProjectGroupRecord", "Group")
                        .WithMany("Projects")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Aeges.Storage.Sqlite.Entities.RunnerExecutionRecord", b =>
                {
                    b.HasOne("Aeges.Storage.Sqlite.Entities.TaskIterationRecord", "Iteration")
                        .WithMany("RunnerExecutions")
                        .HasForeignKey("IterationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aeges.Storage.Sqlite.Entities.TaskRecord", "Task")
                        .WithMany("RunnerExecutions")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Iteration");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Aeges.Storage.Sqlite.Entities.RuntimeEventRecord", b =>
                {
                    b.HasOne("Aeges.Storage.Sqlite.Entities.TaskIterationRecord", "Iteration")
                        .WithMany("RuntimeEvents")
                        .HasForeignKey("IterationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Aeges.Storage.Sqlite.Entities.MachineRecord", "Machine")
                        .WithMany("RuntimeEvents")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Aeges.Storage.Sqlite.Entities.TaskRecord", "Task")
                        .WithMany("RuntimeEvents")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Iteration");

                    b.Navigation("Machine");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Aeges.Storage.Sqlite.Entities.TalkMessageRecord", b =>
                {
                    b.HasOne("Aeges.Storage.Sqlite.Entities.TalkSessionRecord", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Aeges.Storage.Sqlite.Entities.TaskIterationRecord", b =>
                {
                    b.HasOne("Aeges.Storage.Sqlite.Entities.TaskRecord", "Task")
                        .WithMany("Iterations")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Aeges.Storage.Sqlite.Entities.TaskRecord", b =>
                {
                    b.HasOne("Aeges.Storage.Sqlite.Entities.MachineRecord", "Machine")
                        .WithMany("Tasks")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Aeges.Storage.Sqlite.Entities.ProjectRecord", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Machine");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Aeges.Storage.Sqlite.Entities.MachineRecord", b =>
                {
                    b.Navigation("RuntimeEvents");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Aeges.Storage.Sqlite.Entities.ProjectGroupRecord", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Aeges.Storage.Sqlite.Entities.ProjectRecord", b =>
                {
                    b.Navigation("Locks");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Aeges.Storage.Sqlite.Entities.TalkSessionRecord", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Aeges.Storage.Sqlite.Entities.TaskIterationRecord", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("Artifacts");

                    b.Navigation("RunnerExecutions");

                    b.Navigation("RuntimeEvents");
                });

            modelBuilder.Entity("Aeges.Storage.Sqlite.Entities.TaskRecord", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("Artifacts");

                    b.Navigation("Iterations");

                    b.Navigation("Locks");

                    b.Navigation("RunnerExecutions");

                    b.Navigation("RuntimeEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
